version: '3.8'

services:
  api:
    build:
      context: ./api-service
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./api-service:/usr/src/app
    depends_on:
      - redis

  crawler:
    build:
      context: ./crawler-service
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3002"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./crawler-service:/usr/src/app
      - ./crawler-service/pages:/usr/src/app/pages
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data

volumes:
  pages:
  redis-data: